# Generated by Django 3.1.2 on 2021-01-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytvideos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytvideo',
            name='created_by',
        ),
    ]
