# Generated by Django 3.1.2 on 2021-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytvideos', '0002_remove_ytvideo_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ytvideo',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
